name: Build Executable (GUI)

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'banners.yml'
      - 'requirements.txt'
      - 'main.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'banners.yml'
      - 'requirements.txt'
      - 'main.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller -F -w `
          --add-data "banners.yml;." `
          --name "SR-Gacha" `
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SR-Gacha
        path: dist/
